name: Disable Workflow Video

on:
  push:
    branches: [ main ]

    jobs:
      disable:
        runs-on: ubuntu-latest

        steps:
          - name: Neeraj 
            run: echo "Disable Workflow Video DevOps"
